package com.castcle.android.core.constants

const val DATABASE_NAME = "CastcleDatabase"
const val DATABASE_VERSION = 21
const val TABLE_ACCESS_TOKEN = "accessToken"
const val TABLE_CAST = "casts"
const val TABLE_COMMENT = "comment"
const val TABLE_CONTENT = "content"
const val TABLE_COUNTRY_CODE = "countryCode"
const val TABLE_FEED = "feed"
const val TABLE_FOLLOWING_FOLLOWERS = "followingFollowers"
const val TABLE_LINK_SOCIAL = "linkSocial"
const val TABLE_LOAD_KEY = "loadKey"
const val TABLE_NOTIFICATION_BADGES = "notificationBadges"
const val TABLE_PROFILE = "profile"
const val TABLE_RECENT_SEARCH = "recentSearch"
const val TABLE_RECURSIVE_REFRESH_TOKEN = "recursiveRefreshToken"
const val TABLE_SEARCH = "search"
const val TABLE_SEARCH_KEYWORD = "searchKeyword"
const val TABLE_SYNC_SOCIAL = "syncSocial"
const val TABLE_USER = "user"
const val TABLE_WHO_TO_FOLLOW = "whoToFollow"